### ISSUE TITLE
Fix Graph if there are no files

### ISSUE THREAD

**Issue by Villy-P** [Villy-P/File-Makeup-Viewer#28]
In the Webview, if there are no files, the graph.

1. Go to an empty directory
2. Open `File Makeup Viewer`

Instead, It should display something like "There are no files that match your query"

![image](https://github.com/user-attachments/assets/2856d1d7-ffff-488d-bd69-8fef3b88ee6c)

**Comment by NguyenNguyen205** [comment]
Hi, I want to make a little contribution. I've fix this bug, but I don't know if the fix is inline with the desired behavior, so I record a little demo, if you think it's good, then I can make a pull request. I didn't implement FileDeleteEvent from VS Code API for the solution, and only use basic condition checking.

https://github.com/user-attachments/assets/56d53233-de08-4359-a0b1-ca829ddbbf56

**Comment by Villy-P** [comment]
This looks great! If you could also hide the dropdown menu if there are no directories, that would be great, so it only has the Header and the "No files were found" message. Thank you very much!
